# Generated by Django 3.2.5 on 2022-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
