# Generated by Django 3.2.5 on 2022-08-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer2',
            field=models.TextField(default=''),
        ),
    ]
