# Generated by Django 3.2.5 on 2022-08-01 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_quiz_answer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
